getLocalized = ->
   locale = (navigator.language || navigator.userLanguage).substring(0,2)
   localization[locale]

localization = {
   en: {
      username: "Username"
      password: "Password"
      new_entry: "New Entry"
      save: "Save"
      cancel: "Cancel"
      title: "Title"
      edit: "Edit"
      'delete': "Delete"
      login: "Show Passwords"
      register: "Register"
      back: "Back"
      passwords: "Passwords"
      search: "Search entries"
      uppercase: "Uppercase"
      details: "Details"
      generator: "Generator"
      numbers: "Numbers"
      special_characters: "Special Characters"
      length: "Length"
      generate: "Generate"
      generator: "Generator"
      passwords: "Passwords"
      share: "Send per Email"
      username_not_found: "Your entered username does not exist. As a new user you should register first."
      authentification_failed: "The entered username or password is incorrect."
   }
   de: {
      username: "Benutzername"
      password: "Passwort"
      new_entry: "Neuer Eintrag"
      save: "Speichern"
      cancel: "Abbrechen"
      title: "Titel"
      edit: "Bearbeiten"
      'delete': "Löschen"
      login: "Passwörter anzeigen"
      register: "Registrieren"
      back: "Zurück"
      passwords: "Passwörter"
      search: "Einträge durchsuchen"
      uppercase: "Großbuchstaben"
      details: "Details"
      generator: "Generator"
      numbers: "Zahlen"
      special_characters: "Sonderzeichen"
      length: "Länge"
      generate: "Generieren"
      generator: "Generator"
      passwords: "Passwörter"
      share: "Per E-Mail versenden"
      username_not_found: "Der angegebene Benutzername existiert nicht. Als neuer Benutzer musst du dich erst registrieren."
      authentification_failed: "Der angegebene Benutzername oder das Passwort ist falsch."
   }
}